name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Build release apk (Phone)
      run: ./gradlew app:assembleFullRelease

    - name: Build release apk (Wear)
      run: ./gradlew wear:assembleFullRelease

    #- name: List files in the repository
    #  run: |
    #    ls -aR ${{ github.workspace }}

    - name: Setup build tool version variable
      shell: bash
      run: |
        BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
        echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
        echo Last build tool version is: $BUILD_TOOL_VERSION
        
    - name: Sign App (Phone)
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/full/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: 'key0'
        keyStorePassword: 'David1keystore'
        keyPassword: 'David1key'
      env:
        BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

    - name: Sign App (Wear)
      uses: r0adkll/sign-android-release@v1
      id: sign_app_wear
      with:
        releaseDirectory: wear/build/outputs/apk/full/release  # Ensure correct path for Wear OS
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}  # Reusing the same signing key
        alias: 'key0'
        keyStorePassword: 'David1keystore'
        keyPassword: 'David1key'
      env:
        BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

    - name: Upload APK Release (Phone)
      uses: actions/upload-artifact@v4
      with:
        name: APK release generated
        path: app/build/outputs/apk/full/release/app-full-release-unsigned-signed.apk

    - name: Upload APK Release (Wear)
      uses: actions/upload-artifact@v4
      with:
        name: APK release generated (Wear)
        path: wear/build/outputs/apk/full/release/wear-full-release-unsigned-signed.apk

    #- name: Releasing using Hub
    #  uses: sangatdesai/release-apk@main
    #  env:
    #   GITHUB_TOKEN: ${{ secrets.TOKEN }}
    #   APP_FOLDER: app
